### ISSUE TITLE
[Suggestion] Use tags for articles in separate lines

### ISSUE THREAD

**Issue by bhavykhatri** [DevopediaOrg/webapp#520]
Current Behavior: 
![image](https://user-images.githubusercontent.com/26280748/111277545-93d21a80-865e-11eb-9562-c1ed307164bb.png)

Suggested Behavior:
![image](https://user-images.githubusercontent.com/26280748/111277581-a187a000-865e-11eb-8532-bb0a73657032.png)

Advantage: In current behavior it looks like there are two separate tags due to the discontinuity. Changing anchor tag to display: inline-block will resolve thee issue.

**Comment by arvindpdmn** [comment]
It's a good point but there are other issues to consider:
- If the tag is very long, we would have to wrap it anyway. Truncating it is an option, which we have not opted for at the moment.
- There's limited real-estate on the screen. We don't allow scrolling on this panel since the design is sticky. Putting each tag on a separate line may lead to overflow.

Anyway, we'll keep this open for possible enhancements.

**Comment by arvindpdmn** [comment]
Closing without any action for the above reasons.
