### ISSUE TITLE
Why are we showing unpublished articles in right rail entity pane.

### ISSUE THREAD

**Issue by bhavykhatri** [DevopediaOrg/webapp#522]
Why are we showing unpublished articles in right rail? For e.g. when I navigate to this article https://devopedia.org/reinforcement-learning# I am seeing unpublished articles related to Q learning etc. What is the rationale behind such step?

**Comment by arvindpdmn** [comment]
Good observation. Unpublished articles are not visible to visitors. Only logged in users can see them. I assume you're seeing them because you're logged into the Devopedia system.

The reason these are shown to logged in users, who are also authors, is so that they can edit and improve the article. Any author can improve the article. The original author may not have time to complete the article. Once article reaches a certain quality, it will be published.
