### ISSUE TITLE
Handle old URL request after article's title has been changed

### ISSUE THREAD

**Issue by santoshvh** [DevopediaOrg/webapp#9]
Hi Arvind logging in a new issue for your testing

**Comment by arvindpdmn** [comment]
One option is to handle the redirection in Apache but this is not recommended. This is because the old URL might now point to a valid but a different article. For example, topicA is renamed and replaces current topicB. No article is now named as topicA. topicB renamed to new topicC.

So requests to topicA should redirect to new topicB because topicA no longer exists. Requests to topicB will point to current topicB because it exists. However, the system could be made more intelligent and redirect it based on referrers. Referring URLs might suggest the context.

Internally, within Devopedia, links are generated on the fly but really more study is needed to see how feasible is this method.
